Fix Rest and DB Interceptors
inspector-apm/inspector-spring pull request #3
Opened 2024-09-19 16:38 UTC by grove693

Changes:
 - added logging via slf4j api
 - fixed RestInterceptor issue with consuming the http request
 - replaced HibernateInterceptor with JDBCInterceptor which intercepts queryes/statements at the JDBC level
      - used **p6spy-spring-boot-starter** wrapper library for the jdbc interceptor functionality
            - official repo [here](https://github.com/gavlyukovskiy/spring-boot-data-source-decorator) 
      - the underlying library providing the  interceptor functionality is **P6spy**:
            -  P6Spy is intended to be a database logging library and by default it intercepts and logs every SQL statement
                  - official docs [here](https://p6spy.readthedocs.io/en/latest/configandusage.html) 
            - in order to disable the default logging by P6spy I have added the **spy.properties** which is the property file needed to configure the P6Spy library
                 - normally, the P6Spy logging behavior should have been disabled by the **p6spy-spring-boot-starter** wrapper library but its newer versions have compatibility issues with Spring Boot v 2.x
                      - check the issue here: [here](https://github.com/gavlyukovskiy/spring-boot-data-source-decorator/issues/101)

2024-10-02 14:59 UTC, ilvalerione requested changes

2024-10-02 14:59 UTC, ilvalerione commented on src/main/java/dev/inspector/spring/utils/http/request/CachedBodyServletInputStream.java
> +        // TODO: Not yet implemented
@grove693 What does it mean?

2024-10-03 13:23 UTC, grove693 commented on src/main/java/dev/inspector/spring/utils/http/request/CachedBodyServletInputStream.java
> +        // TODO: Not yet implemented
I left the TODO by mistake, there is no implementation needed for the method, will remove the TODO

2024-10-03 13:39 UTC, ilvalerione approved these changes

2024-10-03 13:48 UTC, merged